apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp
  labels:
    app: pyapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
        - name: pyapp
          image: ashis1099/gha-pyapp:b3e28ef80bde3ea8097bef5082b676f62fbe190a
          ports:
            - containerPort: 8000
