apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp
  labels:
    app: pyapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
        - name: pyapp
          image: ashis1099/gha-pyapp:5ca510c92cc00d4957f820322211470f8fafe4d0
          ports:
            - containerPort: 8000
